language: python
python:
  - 3.7
install:
  - pip install -r requirements.txt
script:
  - pytest --cov=./src/autodiffcst/
after_success:
- bash <(curl -s https://codecov.io/bash) -t 2353b173-0e01-4f2e-88fc-12b7fd616f01

